### ISSUE TITLE
Running Test cases.

### ISSUE THREAD

**Issue by TeddyGammel** [Raizlabs/DBFlow#1023]
DBFlow Version:3.1.1
Issue Kind (Bug, Question, Feature): Test cases

Description: 
Hi,

I am currently writing an android library project which uses DBFlow. Via gradle I am able to get hold of the classes in dbflow library. However when I run a test cases I get the following error:
Error:A problem occurred configuring root project '<ApplicationProject-Name>'.

> Could not resolve all dependencies for configuration ':_debugCompile'.
> Could not find com.github.Raizlabs.DBFlow:dbflow-core:3.1.1.
>      Searched in the following locations:
>          https://repo1.maven.org/maven2/com/github/Raizlabs/DBFlow/dbflow-core/3.1.1/dbflow-core-3.1.1.pom
>          https://repo1.maven.org/maven2/com/github/Raizlabs/DBFlow/dbflow-core/3.1.1/dbflow-core-3.1.1.jar
>          file:/C:/Users/<Username>/AppData/Local/Android/sdk/extras/android/m2repository/com/github/Raizlabs/DBFlow/dbflow-core/3.1.1/dbflow-core-3.1.1.pom
>          file:/C:/Users/<Username>/AppData/Local/Android/sdk/extras/android/m2repository/com/github/Raizlabs/DBFlow/dbflow-core/3.1.1/dbflow-core-3.1.1.jar
>          file:/C:/Users/<Username>/AppData/Local/Android/sdk/extras/google/m2repository/com/github/Raizlabs/DBFlow/dbflow-core/3.1.1/dbflow-core-3.1.1.pom
>          file:/C:/Users/<Username>/AppData/Local/Android/sdk/extras/google/m2repository/com/github/Raizlabs/DBFlow/dbflow-core/3.1.1/dbflow-core-3.1.1.jar
>          file:/C:/Users/<Username>/AppData/Local/Android/sdk/extras/m2repository/com/github/Raizlabs/DBFlow/dbflow-core/3.1.1/dbflow-core-3.1.1.pom
>          file:/C:/Users/<Username>/AppData/Local/Android/sdk/extras/m2repository/com/github/Raizlabs/DBFlow/dbflow-core/3.1.1/dbflow-core-3.1.1.jar
>      Required by:
>          :<ApplicationProject-Name>:unspecified > <ApplicationProject-Name>:<LibraryProject-name>:unspecified

I get similar ouputs for dbflow, and dbflow-sqlcipher libraries versions 3.1.1. I have added the appropriate code in gradle as suggested (the jitpack link, jcenter etc.). 
I am not getting compilation errors in the code. The '_Adapter' and '_Table' classes are getting generated. But when running the test cases, i get the error above for all the 3 libraries. Kindly help me out here ASAP.

Thank you.

**Comment by TeddyGammel** [comment]
@agrosner request your help on this issue. Thank you.

**Comment by TeddyGammel** [comment]
@agrosner , this issue was resolved but the fix was done on the build.gradle file of the application project. Shouldn't the code added in the build.gradle of the library project alone suffice?

**Comment by ovidiucp** [comment]
One thing you need to understand is that you cannot run regular Android tests using DBFlow or any other database-related library. The problem is that those tests run on your desktop, as opposed to running on a device. DBFlow relies heavily on Android's core SQL library, for which there is no desktop equivalent.

To fix, make sure you put your test code in an `androidTest`, as opposed to just a `test`. The former is designed to be run on a real device or the emulator, where the full Android environment is present, including the SQLite libraries.

**Comment by trevjonez** [comment]
Robolectric works well for basic query TDD. Keep in mind that tests that
pass in a robolectric config test may still fail on different devices. Line
wraps in migration statements comes to mind as one that will pass on JVM
and some devices yet fail on other devices.
