### ISSUE TITLE
error: ';' expected in Generated classes

### ISSUE THREAD

**Issue by cnmf** [Raizlabs/DBFlow#258]
in an example generated class from concrete class called FeedModel, FeedModel$Container.java loadFromCursor() has several errors

there are several errors in these generated classes where a semicolon ';' is placed after 2 closing parenthesis ')' when there should only be 1 closing parenthesis.

**Comment by OptimistNot** [comment]
Same problem here. dk why, when removed private worked perfectly

**Comment by agrosner** [comment]
Not sure how that happened but what does your model look like? Just curious about the `;` after 2 closing parenthesis issue.

**Comment by cnmf** [comment]
i've removed usage of dbflow because of a few issues (generated files were causing compile time errors as described above, one to many relationships seemed to work sometimes but not always) but the example model causing issues was:

public class FeedModel extends BaseModel {

    public interface Columns extends BaseColumns {
        String NAME = "col_name";
    }
    @Column(name = Columns._ID)
    @PrimaryKey(autoincrement = true)
    public long id;

    @Column(name = Columns.NAME)
    public String name;
}

i basically had to remove all getters/setters and change the private fields to public which was not fun.

**Comment by OptimistNot** [comment]
my model:

@Table(databaseName = GAUDIDatabase.DB_NAME, tableName = AQL.ENDPOINT)
@TableEndpoint(name = AQL.ENDPOINT, contentProviderName = "GAUDIContentProvider")
@ModelContainer
public class AQL extends BaseModel{

    public static final String ENDPOINT = "AQL";

    @ContentUri(path = AQL.ENDPOINT,
            type = ContentUri.ContentType.VND_MULTIPLE + ENDPOINT)
    public static Uri CONTENT_URI = ContentProviderUtils.buildUri(ENDPOINT);

    public interface Columns {
        String AQL_ID = "aql_id";
        String AQL_NAME = "aql_name";
        String AQL_SERVER_ID = "aql_server_id";
        String AQL_TIMESTAMP = "aql_timestamp";
    }

    @Column(name = Columns.AQL_ID)
    @PrimaryKey(autoincrement = true)
    Long aql_id;

    @Column(name = Columns.AQL_NAME)
    String aql_name;

    @Column(name = Columns.AQL_SERVER_ID)
    Long server_id;

    @Column(name = Columns.AQL_TIMESTAMP)
    DateTime timestamp;

all were private fields...had to remove them cz of exception

**Comment by agrosner** [comment]
If you want you're fields as private, you can add _accessors_ of the fields in the format of: 
fieldName => getFieldName(), setFieldName()

As long as those methods are accessible.

**Comment by OptimistNot** [comment]
i'm sorry but i don't think it's possible... even with accessors my containers in toModel() using model.fieldName that gives me access error and still getting ; error in modelContainer.put(), it generates more ")" then should. 
ex: modelContainer.put("aql_id",null));
Thank you!

**Comment by eboissonneault** [comment]
Same issue here. It seems to always happen when I attempt using @ModelContainer

**Comment by R4md4c** [comment]
Same issue here, as OptimistNot stated, there is an unnecessary ")" that makes this compile error.

**Comment by agrosner** [comment]
will check this out for `2.2`

**Comment by R4md4c** [comment]
Are sure that it is fixed in in 2.2 ? I've just checked out this version and the same problem happen when I annotate a BaseModel class with @ModelContainer annotation.

**Comment by agrosner** [comment]
Sorry guys! it will be in `2.2.1`.

**Comment by 0ximDigital** [comment]
Hi, this bug still exists in 2.2.1 .
It occures with @ModelContainer annotation
