### ISSUE TITLE
[3.0] Select all properties from table when joining

### ISSUE THREAD

**Issue by simplysoft** [Raizlabs/DBFlow#513]
In one query we are selecting a row in the model table based on some where conditions form a foreign table, thus we join the foreign key table. The primary key column name on that foreign table is the same as on the model table, so sometimes the wrong primary key was returned (the one of the foreign table row)

We worked around the issue by creating a similar property as `Property.ALL_PROPERTY`:
```
private Property<Pass> ALL_MODEL_PROPERTY = new Property(Model.class, "*") {

    @Override public String toString() {
      return FlowManager.getTableName(Model.class) + "." + getNameAlias().getAliasNameRaw();
    }
  };
```

This feels very hackish, so it would be nice to have a cleaner way to get such a property to only select all properties from a single table when joining multiple ones.

**Comment by agrosner** [comment]
Are you using the `Property.withTable()` method?

**Comment by simplysoft** [comment]
Yes, I'm using Property.withTable for the join & where conditions

**Comment by mhemmings** [comment]
+1 for this.

I was using `getAllColumnProperties()` for the select, but this fails if there are ambiguous column names. Need a way for `getAllColumnProperties()` the respect table aliases as set by `as()`

**Comment by agrosner** [comment]
this should be fixed in `develop`/3.0.0

**Comment by DoubleTime** [comment]
Is this really fixed?

I am trying to get all property of one table still getting ambiguous error.
Using 3.1.1 version.

**Comment by schatekar** [comment]
@agrosner  How do I find out which commit corresponds to fix of this issue?

**Comment by rhespanhol** [comment]
Did anyone was able to sort this out? I'm also having the ambigous error

**Comment by trevjonez** [comment]
Here is a method that takes care of the ambiguous issue when it is a result of a join query.
```java
@NonNull
static IProperty allFromTable(@NonNull Class<? extends Model> tableClass)
{
    require(tableClass).isNotNull();
    return new Property(tableClass, NameAlias.rawBuilder("*").build()).withTable();
}
```
Results in a query something like this:
```sql
SELECT `TABLENAME`.* FROM ...
```

**Comment by xanscale** [comment]
@trevjonez this is project specific code or there is in the in DBFlow lib?

**Comment by trevjonez** [comment]
What I posted was custom. I believe something was added to the library to support it though

**Comment by xanscale** [comment]
@trevjonez  i don't see anything like that

ps why not put table name always ?

**Comment by trevjonez** [comment]
https://github.com/Raizlabs/DBFlow/pull/1273 was where we had talked about doing something similar. @agrosner do you have a link to the alluded static method?

**Comment by agrosner** [comment]
`Property.allProperty(MyTable.class)` or in kotlin `MyTable::class.allProperty()`

**Comment by xanscale** [comment]
@trevjonez @agrosner I love you :)
