### ISSUE TITLE
Using foreign key with integer type and generated Adapter compare int with null

### ISSUE THREAD

**Issue by ManhLQ** [Raizlabs/DBFlow#641]
Firstly, I will talk about my database schema.

> **Collection**  (`msg_key` INTEGER PRIMARY KEY , `message_id` INTEGER, ...)
>
> **Message** (`message_id` : INTEGER PRIMARY KEY, ...)

And my Java code on same package,

`Message` class:

    @Table(database = MyDatabase.class, name = Constants.TBL_MESSAGE, allFields = true)
    public class Message extends BaseModel {
    
        @PrimaryKey
        int message_id;
        String description;
    }

`Collection` class:

    @Table(database = MyDatabase.class, name = Constants.TBL_COLLECTION, allFields = true)
    public class Collection extends BaseModel {
        @Column(setterName = "setMsg_key", getterName = "getMsg_key")
        @PrimaryKey
        private int msg_key;
    
        @Column(setterName = "setMessage_id", getterName = "getMessage_id")
        @ForeignKey(references = {
                @ForeignKeyReference(columnType = Integer.class,
                        columnName = Constants.TBL_COL_MSG,
                        foreignKeyColumnName = Constants.TBL_MSG_ID)}
                , saveForeignKeyModel = false)
        private Message message_id;
    
        public void setMessage_id(Message message_id) {
            this.message_id = message_id;
        }
    
        public void setMsg_key(int msg_key) {
            this.msg_key = msg_key;
        }
    
        public int getMsg_key() {
            return msg_key;
        }
    
        public Message getMessage_id() {
            return message_id;
        }
    }

As [`DBFlow` document][1], 

> All fields must be public or package private as the _Adapter class
> needs access to them. NOTE: Package private fields need not be in the
> same package as DBFlow will generate the necessary access methods to
> get to them. 

> Or private ONLY when you specify get{Name}() and
> set{Name}(columnType) methods for a column named {name}. This can be
> configured.

But when I build the application, android studio throw an error that 
> Error: incomparable types: int and `<null>`

Then I check `generated code` by DBFlow and realize its compare int with null.

[![enter image description here][2]][2]

I'm not sure it's `DBFlow` bug or I missing/wrong configuration on somewhere?
Please give me your suggest/solutions.

== Update ==

I'm using DBFlow ver 3.0.0 beta 3

Thanks!

  [1]: https://github.com/Raizlabs/DBFlow/blob/master/usage/DBStructure.md
  [2]: http://i.stack.imgur.com/v6Gq7.png

**Comment by GrahamRogers** [comment]
I came across the same problem and fixed it with https://github.com/Raizlabs/DBFlow/pull/643.

**Comment by ManhLQ** [comment]
@GrahamRogers: thanks, It's help me a lot!

**Comment by GrahamRogers** [comment]
Did my pull request fix your issue? If so, you should reopen this issue until my pull request has been included.

**Comment by ManhLQ** [comment]
@GrahamRogers : Thanks, it's solved my problem! I re-opened.

**Comment by agrosner** [comment]
this was fixed in last version.

**Comment by bblia** [comment]
i'm still seeing this on 3.1.1 

![image](https://cloud.githubusercontent.com/assets/4870878/16645456/f3c61072-43d8-11e6-8070-9c71c6a72edd.png)

in the top model class:
![image](https://cloud.githubusercontent.com/assets/4870878/16645472/02cc5158-43d9-11e6-8155-4d5432b77400.png)

in the message class:
![image](https://cloud.githubusercontent.com/assets/4870878/16645479/0d4fded8-43d9-11e6-8945-81aa63f78328.png)

is there something i'm missing? or should i pin to an older version?

**Comment by alexbeville** [comment]
I'm currently facing the same issue :

<img width="505" alt="capture d ecran 2016-07-08 a 11 17 41" src="https://cloud.githubusercontent.com/assets/1587217/16682991/bf990fae-44fd-11e6-8de0-83dec382bec1.png">
<img width="464" alt="capture d ecran 2016-07-08 a 11 18 16" src="https://cloud.githubusercontent.com/assets/1587217/16682998/c740f2c6-44fd-11e6-9e5a-eea48f530a7b.png">
<img width="199" alt="capture d ecran 2016-07-08 a 11 18 26" src="https://cloud.githubusercontent.com/assets/1587217/16682999/c9a3a23e-44fd-11e6-9e0e-e8d2d28fef9c.png">

**Comment by nithdi** [comment]
same here on 3.1.1

**Comment by GrahamRogers** [comment]
@bblia Android Studio has correctly colored the fields and is underlining more than model.last_message.id, suggesting that the fields are there you have a different issue.

@alexbeville You want model.getCategory().getId()

**Comment by alexbeville** [comment]
Indeed, it should be getId();

The problem was that I had an existing db file, and my model class should fit the database scheme.

So instead of doing this, and make it more complex, I decide to forget the existing db file, and remove the @ForeignKeyReference

It works now but the issue still exists for other projects

**Comment by bblia** [comment]
It's comparing an int with null in the generated adapter class, isn't that the same issue as originally reported? 

Sorry if it's my mistake, but it seems like the same issue to me haha

**Comment by GrahamRogers** [comment]
You're right, I was thinking of a different issue. You might want to create a new issue instead of commenting on a closed one though.
