### ISSUE TITLE
Concurrent database access

### ISSUE THREAD

**Issue by romulof** [Raizlabs/DBFlow#686]
My app does a big transaction in a background thread to sync data. Before using DBFlow I was opening and closing the connection every time I accessed the database and in the case of transaction I kept the `SQLiteDatabase` opened until it finished. I had to protect the acquisition of `SQLiteDatabase` object with a mutex and the app worked perfectly.

After I migrated to DBFlow the main thread started locking up a lot, because the background thread was doing the transition, so I had to turn my sync procedure into a spaghetti code to use DBFlow transaction queue, specially because I could not enqueue a large batch of models or else the main thread locked again. I got LOTs of problems because of this architecture, but I managed to make it work.

Today I discovered this option on Android documentation, and I think I found the holy grail of concurrent database access.

http://developer.android.com/reference/android/database/sqlite/SQLiteDatabase.html#enableWriteAheadLogging()

Has anyone here already used it? I think it should be great to have an option in DBFlow to enable this, since it prevents us to access the `SQLiteDatabase` object.

**Comment by agrosner** [comment]
Potentially use it but that is not supported on all versions. Synchronization of the queue should be fixed in latest version. I would encourage you to check it out.

**Comment by AlyssonPHN** [comment]
Please release access to SQLiteDatabase.

**Comment by bitterinfant** [comment]
I'm using the latest version (def dbflow_version = "4.2.4") and it feels like this is still happening as I haven't been able to transition all "reads" into async reads but I believe I have all "writes" as being enclosed in a transaction and asynchronous.  I agree with AlyssonPHN, I have been scouring Google and your reference docs and cannot find how I might set the  enableWriteAheadLogging() flag without having access to the SQLiteDatabase object which I haven't figured out how to get through in DBFlow objects.

**Comment by bitterinfant** [comment]
I figured it out--when your helper loads (I'm using Cipher) you can overload the onOpen or onCreate and get access to the "android db". lol.        public SQLCipherHelperImpl(DatabaseDefinition databaseDefinition, DatabaseHelperListener listener) {
            super(databaseDefinition, listener);
        }

        @Override
        public void onCreate(net.sqlcipher.database.SQLiteDatabase db) {
            db.setLockingEnabled(false);
            super.onCreate(db);
        }

        @Override
        public void onOpen(net.sqlcipher.database.SQLiteDatabase db) {
            db.setLockingEnabled(false);
            super.onOpen(db);

        }

**Comment by egette** [comment]
The complete class :

public class SQLCipherHelperImpl extends SQLCipherOpenHelper {

    public SQLCipherHelperImpl(DatabaseDefinition databaseDefinition, DatabaseHelperListener listener) {
        super(databaseDefinition, listener);
    }
    @Override
    public void onCreate(net.sqlcipher.database.SQLiteDatabase db) {
        db.setLockingEnabled(false);
        super.onCreate(db);
    }

    @Override
    public void onOpen(net.sqlcipher.database.SQLiteDatabase db) {
        db.setLockingEnabled(false);
        super.onOpen(db);
    }

    @Override
    protected String getCipherSecret() {
        return "CIPHERSTRING";
    }

}
