### ISSUE TITLE
Build Failed When Using OneToMany.Method.ALL / OneToMany.Method.DELETE

### ISSUE THREAD

**Issue by vietmh** [Raizlabs/DBFlow#884]
**DBFlow Version:** 3.0.1
**Issue Kind (Bug, Question, Feature):** Question

**Description:** 
My project cannot be built when I used OneToMany.Method.ALL / OneToMany.Method.DELETE for my getter method. It works fine with OneToMany.Method.SAVE. Below are the built error and my code :

The error got from "./gradlew clean assemble --debug --stacktrace" : 
```
20:36:58.800 [ERROR] [org.gradle.BuildExceptionReporter] Caused by: java.lang.NoSuchMethodError: com.squareup.javapoet.CodeBlock.of(Ljava/lang/String;[Ljava/lang/Object;)Lcom/squareup/javapoet/CodeBlock;
20:36:58.800 [ERROR] [org.gradle.BuildExceptionReporter] 	at com.raizlabs.android.dbflow.processor.definition.OneToManyDefinition.writeDelete(OneToManyDefinition.java:103)
20:36:58.800 [ERROR] [org.gradle.BuildExceptionReporter] 	at com.raizlabs.android.dbflow.processor.definition.method.OneToManyDeleteMethod.getMethodSpec(OneToManyDeleteMethod.java:44)
20:36:58.800 [ERROR] [org.gradle.BuildExceptionReporter] 	at com.raizlabs.android.dbflow.processor.definition.TableDefinition.writeAdapter(TableDefinition.java:642)
20:36:58.800 [ERROR] [org.gradle.BuildExceptionReporter] 	at com.raizlabs.android.dbflow.processor.model.ProcessorManager.handle(ProcessorManager.java:340)
20:36:58.800 [ERROR] [org.gradle.BuildExceptionReporter] 	at com.raizlabs.android.dbflow.processor.DBFlowProcessor.process(DBFlowProcessor.java:98)
20:36:58.800 [ERROR] [org.gradle.BuildExceptionReporter] 	at com.sun.tools.javac.processing.JavacProcessingEnvironment.callProcessor(JavacProcessingEnvironment.java:794)
20:36:58.800 [ERROR] [org.gradle.BuildExceptionReporter] 	at com.sun.tools.javac.processing.JavacProcessingEnvironment.discoverAndRunProcs(JavacProcessingEnvironment.java:705)
20:36:58.800 [ERROR] [org.gradle.BuildExceptionReporter] 	at com.sun.tools.javac.processing.JavacProcessingEnvironment.access$1800(JavacProcessingEnvironment.java:91)
20:36:58.800 [ERROR] [org.gradle.BuildExceptionReporter] 	at com.sun.tools.javac.processing.JavacProcessingEnvironment$Round.run(JavacProcessingEnvironment.java:1035)
20:36:58.800 [ERROR] [org.gradle.BuildExceptionReporter] 	at com.sun.tools.javac.processing.JavacProcessingEnvironment.doProcessing(JavacProcessingEnvironment.java:1176)
20:36:58.800 [ERROR] [org.gradle.BuildExceptionReporter] 	at com.sun.tools.javac.main.JavaCompiler.processAnnotations(JavaCompiler.java:1170)
20:36:58.800 [ERROR] [org.gradle.BuildExceptionReporter] 	at com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:856)
20:36:58.800 [ERROR] [org.gradle.BuildExceptionReporter] 	at com.sun.tools.javac.main.Main.compile(Main.java:523)
```

And my method :
```
@OneToMany(methods = {OneToMany.Method.DELETE}, variableName = "childs")
public List<Child> getChilds() {
            if (childs == null || events.isEmpty()) {
                childs = SQLite.select()
                        .from(Child.class)
                        .where(Child_Table.parent_id.eq(id))
                        .queryList();
            }
        return childs;
    }
```
Am I missing something ?

Thanks.
Viet

**Comment by agrosner** [comment]
It appears you have another project that uses [JavaPoet](https://github.com/square/javapoet) which does not support that method. So I fixed it in `develop` already.

**Comment by luonganhtuanTMA** [comment]
Hi @agrosner,
This issue has still existed on the pre-release version 4.0.0-beta2 and develop-SNAPSHOT also.
Could you please help to check it!

```
Caused by: java.lang.NoSuchMethodError: com.squareup.javapoet.CodeBlock.of(Ljava/lang/String;[Ljava/lang/Object;)Lcom/squareup/javapoet/CodeBlock;
	at com.raizlabs.android.dbflow.processor.definition.column.ColumnAccessorKt.<clinit>(ColumnAccessor.kt:13)
	at com.raizlabs.android.dbflow.processor.definition.column.ColumnDefinition.addPropertyDefinition(ColumnDefinition.kt:253)
	at com.raizlabs.android.dbflow.processor.definition.TableDefinition.onWriteDefinition(TableDefinition.kt:364)
	at com.raizlabs.android.dbflow.processor.definition.BaseDefinition.getTypeSpec(BaseDefinition.kt:135)
	at com.raizlabs.android.dbflow.processor.utils.WriterUtils.writeBaseDefinition(WriterUtils.kt:16)
	at com.raizlabs.android.dbflow.processor.ProcessorManager.handle(ProcessorManager.kt:292)
	at com.raizlabs.android.dbflow.processor.DBFlowProcessor.process(DBFlowProcessor.java:95)
```
Thanks,
Tuan
